/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BWFxAKVkRMJ
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function LoginPage() {
  return (
    <div className="flex h-screen bg-[#00796b]">
      <div className="m-auto w-full max-w-md p-8 bg-white rounded-lg shadow">
        <h1 className="text-3xl font-bold text-center">Log In</h1>
        <div className="mt-6 flex justify-between gap-4">
          <Button className="flex-1 bg-[#004d40] text-white">
            <UserIcon className="mr-2" />
            Doctors Portal{"\n"}
          </Button>
          <Button className="flex-1 bg-[#e0f2f1] text-[#004d40]">
            <StoreIcon className="mr-2" />
            Vendors Portal{"\n"}
          </Button>
        </div>
        <div className="mt-8">
          <label className="block text-sm font-medium text-gray-700" htmlFor="username">
            Username
          </label>
          <Input className="mt-1" id="username" placeholder="Username" type="text" />
        </div>
        <div className="mt-4">
          <label className="block text-sm font-medium text-gray-700" htmlFor="password">
            Password
          </label>
          <Input className="mt-1" id="password" placeholder="Password" type="password" />
        </div>
        <div className="mt-6">
          <Button className="w-full bg-[#004d40] text-white">Login</Button>
        </div>
      </div>
      <div className="m-auto">
        <SirenIcon className="text-white" />
      </div>
    </div>
  )
}


function UserIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0-4-4H9a4 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function StoreIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m2 7 4.41-4.41A2 2 0 1 7.83 2h8.34a2 1.42.59L22" />
      <path d="M4 12v8a2 2 0 2h12a2 2-2v-8" />
      <path d="M15 22v-4a2 2 0 0-2-2h-2a2 0-2 2v4" />
      <path d="M2 7h20" />
      <path d="M22 7v3a2 2 0 1-2 2v0a2.7 2.7 1-1.59-.63.7.7 0-.82 0A2.7 1 16 12a2.7 12 8 4 12v0a2 1-2-2V7" />
    </svg>
  )
}


function SirenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 12a5 5 0 1 5-5v0a5 5v6H7v-6Z" />
      <path d="M5 20a2 2 0 1 2-2h10a2 2v2H5v-2Z" />
      <path d="M21 12h1" />
      <path d="M18.5 4.5 18 5" />
      <path d="M2 12h1" />
      <path d="M12 2v1" />
      <path d="m4.929 4.929.707.707" />
      <path d="M12 12v6" />
    </svg>
  )
}
